set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_CROSSCOMPILING TRUE)

set(CMAKE_SYSROOT "${CMAKE_SOURCE_DIR}/sysroots/rpi5")

set(CMAKE_C_COMPILER_TARGET aarch64-linux-gnu)
set(CMAKE_CXX_COMPILER_TARGET aarch64-linux-gnu)

set(RPI5_CPU_FLAG "-mcpu=cortex-a76")
set(RPI5_SYSROOT_FLAG "--sysroot=${CMAKE_SYSROOT}")
set(CMAKE_C_FLAGS "${RPI5_CPU_FLAG} ${RPI5_CPU_FLAG}")
set(CMAKE_CXX_FLAGS "${RPI5_CPU_FLAG} ${RPI5_CPU_FLAG}")
set(CMAKE_EXE_LINKER_FLAGS "${RPI5_CPU_FLAG}")

set(CMAKE_FIND_ROOT_PATH ${CMAKE_SYSROOT})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(VCPKG_TARGET_TRIPLET "arm64-linux")
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
include("${CMAKE_SOURCE_DIR}/vcpkg/scripts/buildsystems/vcpkg.cmake")